<a href="https://colab.research.google.com/github/CatalinaDeras24/elt-data-pipeline-2503242022-/blob/main/notebooks/Bodegas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

In [8]:
url="https://raw.githubusercontent.com/CatalinaDeras24/elt-data-pipeline-2503242022-/refs/heads/main/data/raw/E_bodegas.csv"

In [9]:
df = pd.read_csv(url)

In [10]:
df.head()

  id_bodega       bodega   ubicacion capacidad_m2
0    BOD100   Central 0     Usulután      1292 m2
1    BOD101        Sur 1  San Miguel         2047
2    BOD102    Central 2   Sonsonate       651 m2
3    BOD103  Occidente 3  San Miguel         2250
4    BOD104        Sur 4   Santa Ana          239

Exploración de datos

In [11]:
df.shape

(20, 4)

In [12]:
df.columns

Index(['id_bodega', 'bodega', 'ubicacion', 'capacidad_m2'], dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_bodega     18 non-null     object
 1   bodega        20 non-null     object
 2   ubicacion     20 non-null     object
 3   capacidad_m2  20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

In [57]:
df.isnull().sum()

id_bodega       0
bodega          0
ubicacion       0
capacidad_m2    0
dtype: int64

Limpieza de datos

In [71]:
Bodegas = df.copy()

In [72]:
Bodegas.columns = Bodegas.columns.str.strip().str.lower()

In [73]:
for col in Bodegas.select_dtypes(include='object').columns:
    Bodegas[col] = Bodegas[col].str.strip()

In [74]:
Bodegas['capacidad_m2'] = Bodegas['capacidad_m2'].str.replace('m2', '', regex=False)

In [75]:
Bodegas = Bodegas.replace(['', 'nan', 'None', 'NULL'], pd.NA)

In [76]:
Bodegas = Bodegas.drop_duplicates()

Separar datos válidos y rechazados

In [77]:
validos = Bodegas[
    Bodegas['id_bodega'].notna()
].copy()

In [78]:
rechazados = Bodegas[
    Bodegas['id_bodega'].isna()
].copy()

Motivo de rechazo

In [79]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_bodega']):
        motivos.append("No cuenta con un ID")



    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar archivos

In [80]:
validos.to_csv("Bodegas_curated.csv", index=False)

rechazados.to_csv("Bodegas_rejects.csv", index=False)


Conectar con PostgreSQL Cloud

In [81]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_a5iy_user:wejO7kM3iEylWf1mrkye7dj6P9rI4f6B@dpg-d6qu8ka4d50c73bk4lqg-a.oregon-postgres.render.com/etl_seguros_a5iy"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Cargar datos en PostgreSQL

In [82]:
validos.to_sql(
    'Bodegas_curated',
    engine,
    if_exists='append',
    index=False
)

16

In [83]:
rechazados.to_sql(
    'Bodegas_rejects',
    engine,
    if_exists='append',
    index=False
)

2

Validar la carga

In [90]:
pd.read_sql('SELECT * FROM "Bodegas_curated" LIMIT 20', engine)

   id_bodega       bodega     ubicacion capacidad_m2
0     BOD100    Central 0      Usulután        1292
1     BOD101        Sur 1    San Miguel         2047
2     BOD102    Central 2     Sonsonate         651
3     BOD103  Occidente 3    San Miguel         2250
4     BOD104        Sur 4     Santa Ana          239
5     BOD105    Central 5   La Libertad         1546
6     BOD106    Central 6    San Miguel         1783
7     BOD107  Occidente 7   La Libertad         2181
8     BOD108    Oriente 8     Santa Ana         1359
9     BOD109    Oriente 9     Santa Ana         2097
10    BOD111       Sur 11     Santa Ana         1582
11    BOD112   Central 12     Santa Ana         413
12    BOD113     Norte 13  San Salvador         1062
13    BOD115       Sur 15     Santa Ana         2217
14    BOD116   Oriente 16   La Libertad          788
15    BOD117       Sur 17      Usulután         1904