<a href="https://colab.research.google.com/github/CatalinaDeras24/elt-data-pipeline-2503242022-/blob/main/notebooks/Inventario.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/CatalinaDeras24/elt-data-pipeline-2503242022-/refs/heads/main/data/raw/E_inventario.csv"

In [3]:
df = pd.read_csv(url)

In [4]:
df.head()

  id_inventario id_bodega            item cantidad costo_unitario
0       INV5000    BOD103     Producto 45      359         192.81
1       INV5001    BOD111      Producto 2      419         153.48
2       INV5002    BOD999   Producto 120        58         104.91
3       INV5003    BOD100     Producto 42      422       $ 138.66
4       INV5004    BOD112     Producto 79      257            NaN

Exploracion de datos

In [5]:
df.shape

(166, 5)

In [6]:
df.columns

Index(['id_inventario', 'id_bodega', 'item', 'cantidad', 'costo_unitario'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_inventario   166 non-null    object
 1   id_bodega       161 non-null    object
 2   item            166 non-null    object
 3   cantidad        161 non-null    object
 4   costo_unitario  161 non-null    object
dtypes: object(5)
memory usage: 6.6+ KB

In [8]:
df.isnull().sum()

id_inventario     0
id_bodega         5
item              0
cantidad          5
costo_unitario    5
dtype: int64

Limpieza de datos

In [9]:
Inventario= df.copy()

In [11]:
for col in Inventario.select_dtypes(include='object').columns:
    Inventario[col] = Inventario[col].str.strip()

In [12]:
Inventario['id_bodega']=Inventario['id_bodega'].replace(['', 'nan', 'None', 'NULL'], pd.NA)

In [14]:
Inventario['cantidad'] = (
    Inventario['cantidad']
    .astype(str)
    .str.replace(' unidades', '', regex=False)
    .str.strip()
)

Inventario['cantidad'] = pd.to_numeric(Inventario['cantidad'], errors='coerce')

In [15]:
Inventario['costo_unitario'] = (
    Inventario['costo_unitario']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.replace('USD', '', regex=False)
    .str.strip()
)


Inventario['costo_unitario'] = pd.to_numeric(
    Inventario['costo_unitario'],
    errors='coerce'
)

In [16]:
Inventario= Inventario.drop_duplicates()

Separar datos válidos y rechazados

In [17]:
validos = Inventario.dropna(
    subset=['id_bodega', 'cantidad', 'costo_unitario']
).copy()

rechazados = Inventario[
    Inventario[['id_bodega', 'cantidad', 'costo_unitario']]
    .isna()
    .any(axis=1)
].copy()

Motivo de rechazo

In [18]:
def motivo(row):
    motivos = []

    if pd.isna(row['id_bodega']):
        motivos.append("No cuenta con id_bodega")

    if pd.isna(row['cantidad']):
        motivos.append("Cantidad vacía")
    elif row['cantidad'] <= 0:
        motivos.append("Cantidad debe ser mayor a 0")

    if pd.isna(row['costo_unitario']):
        motivos.append("Costo unitario vacío")
    elif row['costo_unitario'] <= 0:
        motivos.append("Costo unitario debe ser mayor a 0")

    return ", ".join(motivos)

Exportar archivos

In [19]:
validos.to_csv("Inventario_curated.csv", index=False)

rechazados.to_csv("Inventario_rejects.csv", index=False)

Conectar con PostgreSQL Cloud

In [20]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_a5iy_user:wejO7kM3iEylWf1mrkye7dj6P9rI4f6B@dpg-d6qu8ka4d50c73bk4lqg-a.oregon-postgres.render.com/etl_seguros_a5iy"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 61.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Cargar datos en PostgreSQL

In [21]:
validos.to_sql(
    'Inventario_curated',
    engine,
    if_exists='append',
    index=False
)

143

In [22]:
rechazados.to_sql(
    'Inventario_rejects',
    engine,
    if_exists='append',
    index=False
)

17

Validar la carga

In [24]:
pd.read_sql('SELECT * FROM "Movimientos_curated" LIMIT 40', engine)

   id_movimiento id_inventario tipo_movimiento      fecha cantidad_movimiento
0         ajuste       INV5000          ajuste 2025-05-03                  15
1         ajuste       INV5122          ajuste 2024-06-03                 73
2         ajuste       INV5112          ajuste 2025-04-07                  37
3         salida       INV5002          salida 2024-09-11                  17
4        entrada       INV5082         entrada 2025-02-02                  65
5       traslado       INV5037        traslado 2025-12-01                  74
6       traslado       INV5027        traslado 2024-09-05                  25
7         salida       INV5046          salida 2025-01-07                  16
8       traslado       INV5009        traslado 2024-11-12                  55
9        entrada       INV5152         entrada 2024-04-03                  13
10        salida       INV5111          salida 2025-10-04                 60
11       entrada       INV5007         entrada 2025-05-04                  62
12       entrada       INV5050         entrada 2025-06-04                  34
13        salida       INV5021          salida 2024-07-11                  42
14       entrada       INV5079         entrada 2024-11-06                  31
15        salida       INV5105          salida 2025-11-06                  45
16        salida       INV5109          salida 2025-12-01                  24
17        ajuste       INV5109          ajuste 2024-05-04                  39
18      traslado       INV5063        traslado 2024-05-10                  21
19        ajuste       INV5028          ajuste 2025-02-06                  61
20      traslado       INV5039        traslado 2025-11-02                  15
21       entrada       INV5025         entrada 2025-04-07                  30
22      traslado       INV5017        traslado 2025-01-07                   2
23        ajuste       INV5029          ajuste 2025-10-05                  39
24        salida       INV5022          salida 2025-11-02                  32
25      traslado       INV5022        traslado 2025-12-05                  46
26       entrada       INV5063         entrada 2025-09-02                  60
27      traslado       INV5123        traslado 2024-09-05                  79
28       entrada       INV5109         entrada 2024-07-01                  69
29       entrada       INV5121         entrada 2024-05-05                  46
30       entrada       INV5015         entrada 2025-05-01                  44
31      traslado       INV5095        traslado 2025-06-03                  66
32       entrada       INV5026         entrada 2024-01-13                  57
33      traslado       INV5014        traslado 2024-09-08                  38
34        ajuste       INV5067          ajuste 2025-04-04                  30
35        salida       INV5011          salida 2024-04-07                  21
36        ajuste       INV5013          ajuste 2024-11-03                  38
37      traslado       INV5081        traslado 2024-05-05                  78
38        ajuste       INV5087          ajuste 2025-01-02                  73
39      traslado       INV5139        traslado 2024-05-09                  63