<a href="https://colab.research.google.com/github/CatalinaDeras24/elt-data-pipeline-2503242022-/blob/main/notebooks/Movimientos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/CatalinaDeras24/elt-data-pipeline-2503242022-/refs/heads/main/data/raw/E_movimientos.csv"

In [3]:
df = pd.read_csv(url)

In [4]:
df.head()

  id_movimiento id_inventario tipo_movimiento       fecha cantidad_movimiento
0       MOV9000       INV5000          ajuste  2025-03-05                  15
1       MOV9001       INV5122          ajuste  2024-03-06              73 uds
2       MOV9002       INV5019          salida  2024-05-27                  30
3       MOV9003       INV5110         entrada  2025-01-16                  44
4       MOV9004       INV5152         entrada  2024-08-28                  55

Exploracion de datos

In [5]:
df.shape

(226, 5)

In [6]:
df.columns

Index(['id_movimiento', 'id_inventario', 'tipo_movimiento', 'fecha',
       'cantidad_movimiento'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        226 non-null    object
 1   id_inventario        220 non-null    object
 2   tipo_movimiento      226 non-null    object
 3   fecha                221 non-null    object
 4   cantidad_movimiento  222 non-null    object
dtypes: object(5)
memory usage: 9.0+ KB

In [8]:
df.isnull().sum()

id_movimiento          0
id_inventario          6
tipo_movimiento        0
fecha                  5
cantidad_movimiento    4
dtype: int64

Limpieza de datos

In [24]:
Movimientos= df.copy()

In [25]:
for col in Movimientos.select_dtypes(include='object').columns:
    Movimientos[col] = Movimientos[col].str.strip()

In [26]:
Movimientos['id_movimiento']=Movimientos['tipo_movimiento'].replace(['', 'nan', 'None', 'NULL'], pd.NA)

In [27]:
Movimientos['fecha'] = pd.to_datetime(
    Movimientos['fecha'],
    errors='coerce',
    dayfirst=True
)

In [28]:
Movimientos['fecha']=Movimientos['fecha'].replace(['', 'nan', 'None', 'NULL'], pd.NA)

In [29]:
Movimientos['cantidad_movimiento'] = Movimientos['cantidad_movimiento'].str.replace('uds', '', regex=False)

In [30]:
Movimientos['cantidad_movimiento']=Movimientos['cantidad_movimiento'].replace(['', 'nan', 'None', 'NULL'], pd.NA)

In [31]:
Movimientos= Movimientos.drop_duplicates()

Separar datos válidos y rechazados

In [32]:
validos = Movimientos.dropna(
    subset=['id_inventario', 'fecha', 'cantidad_movimiento']
).copy()

rechazados = Movimientos[
    Movimientos[['id_inventario', 'fecha', 'cantidad_movimiento']]
    .isna()
    .any(axis=1)
].copy()

Motivo de rechazo

In [33]:
def motivo(row):
    motivos = []

    if pd.isna(row['id_inventario']):
        motivos.append("No cuenta con id_inventario")

    if pd.isna(row['fecha']):
        motivos.append("Fecha inválida o vacía")

    if pd.isna(row['cantidad_movimiento']):
        motivos.append("Cantidad de movimiento vacía")

    return ", ".join(motivos)

Exportar archivos

In [34]:
validos.to_csv("Movimientos_curated.csv", index=False)

rechazados.to_csv("Movimientos_rejects.csv", index=False)

Conectar con PostgreSQL Cloud

In [35]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_a5iy_user:wejO7kM3iEylWf1mrkye7dj6P9rI4f6B@dpg-d6qu8ka4d50c73bk4lqg-a.oregon-postgres.render.com/etl_seguros_a5iy"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 32.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Cargar datos en PostgreSQL

In [36]:
validos.to_sql(
    'Movimientos_curated',
    engine,
    if_exists='append',
    index=False
)

69

In [37]:
rechazados.to_sql(
    'Movimientos_rejects',
    engine,
    if_exists='append',
    index=False
)

151

Validar la carga

In [38]:
pd.read_sql('SELECT * FROM "Movimientos_curated" LIMIT 30', engine)

   id_movimiento id_inventario tipo_movimiento      fecha cantidad_movimiento
0         ajuste       INV5000          ajuste 2025-05-03                  15
1         ajuste       INV5122          ajuste 2024-06-03                 73
2         ajuste       INV5112          ajuste 2025-04-07                  37
3         salida       INV5002          salida 2024-09-11                  17
4        entrada       INV5082         entrada 2025-02-02                  65
5       traslado       INV5037        traslado 2025-12-01                  74
6       traslado       INV5027        traslado 2024-09-05                  25
7         salida       INV5046          salida 2025-01-07                  16
8       traslado       INV5009        traslado 2024-11-12                  55
9        entrada       INV5152         entrada 2024-04-03                  13
10        salida       INV5111          salida 2025-10-04                 60
11       entrada       INV5007         entrada 2025-05-04                  62
12       entrada       INV5050         entrada 2025-06-04                  34
13        salida       INV5021          salida 2024-07-11                  42
14       entrada       INV5079         entrada 2024-11-06                  31
15        salida       INV5105          salida 2025-11-06                  45
16        salida       INV5109          salida 2025-12-01                  24
17        ajuste       INV5109          ajuste 2024-05-04                  39
18      traslado       INV5063        traslado 2024-05-10                  21
19        ajuste       INV5028          ajuste 2025-02-06                  61
20      traslado       INV5039        traslado 2025-11-02                  15
21       entrada       INV5025         entrada 2025-04-07                  30
22      traslado       INV5017        traslado 2025-01-07                   2
23        ajuste       INV5029          ajuste 2025-10-05                  39
24        salida       INV5022          salida 2025-11-02                  32
25      traslado       INV5022        traslado 2025-12-05                  46
26       entrada       INV5063         entrada 2025-09-02                  60
27      traslado       INV5123        traslado 2024-09-05                  79
28       entrada       INV5109         entrada 2024-07-01                  69
29       entrada       INV5121         entrada 2024-05-05                  46